// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehxfmpnkymldxpeszepx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoeGZtcG5reW1sZHhwZXN6ZXB4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NzA5NTIsImV4cCI6MjA2MjE0Njk1Mn0.Nuy7QVFoYvK2S19AOa8lIWpjGHMprPRj6SyMNXhsD7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);